
name: Code With Cory
title: null

# Favicon
avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Bash_Logo_Favicon_Colored.svg/120px-Bash_Logo_Favicon_Colored.svg.png"
round-avatar: false



